Iteration reporting
RTKConsortium/RTK pull request #266
Opened 2019-11-08 16:41 UTC by acoussat

First steps towards an iteration reporting system in RTK. The goal is to allow users to plug their own custom callback called on each completion of any iteration filter. This is still a work in progress.

So far only [`rtkSARTConeBeamReconstructionFilter`](https://github.com/acoussat/RTK/blob/iteration-reporting/include/rtkSARTConeBeamReconstructionFilter.h) and [`rtkConjugateGradientConeBeamReconstructionFilter`](https://github.com/acoussat/RTK/blob/iteration-reporting/include/rtkConjugateGradientConeBeamReconstructionFilter.h) have been updated. The simplest way of testing the reporting is by using `rtksart` with the `-v` (verbose) flag.

Allows filters to [observe another filter](https://github.com/acoussat/RTK/blob/dc9c02076b3d818b9061ec67bfb5d5ded5d26fef/applications/rtksart/rtksart.cxx#L124) and invoke a callback upon iteration completion. [Some default callbacks](https://github.com/acoussat/RTK/blob/iteration-reporting/include/rtkIterationCommands.h) were defined but you can easily define your own callbacks by deriving [`IterationCommand`](https://github.com/acoussat/RTK/blob/iteration-reporting/include/rtkIterationCommands.h#L36).

This is done by exploiting the possibilities of [`itk::IterationReporter`](https://itk.org/Doxygen/html/classitk_1_1IterationReporter.html). Note that [`itk::ProgressReporter`](https://itk.org/Doxygen/html/classitk_1_1ProgressReporter.html) also exists but using [`itk::IterationReporter`](https://itk.org/Doxygen/html/classitk_1_1IterationReporter.html) seems more semantically correct to me.

Also note [the trick](https://github.com/acoussat/RTK/blob/iteration-reporting/include/rtkConjugateGradientConeBeamReconstructionFilter.hxx#L394) used for [`rtkConjugateGradientConeBeamReconstructionFilter`](https://github.com/acoussat/RTK/blob/iteration-reporting/include/rtkConjugateGradientConeBeamReconstructionFilter.h). The filter listens to its sub-filter `m_ConjugateGradientFilter` and automatically passes up the notification.

Things left to do:
- [ ] decide whether to use [`itk::IterationReporter`](https://itk.org/Doxygen/html/classitk_1_1IterationReporter.html) or [`itk::ProgressReporter`](https://itk.org/Doxygen/html/classitk_1_1ProgressReporter.html)
- [ ] implement the notification mechanism in all iterative filters

2019-11-12 11:10 UTC, SimonRit requested changes
Looks good! Just a couple of questions / comments. I guess we should propagate this to all iterative algorithms if possible?

2019-11-12 11:10 UTC, SimonRit commented on wrapping/itkIterationReporter.wrap
> +itk_wrap_simple_class("itk::IterationReporter")
Should this be submitted to ITK? Is it actually usable from python?

2019-11-12 11:10 UTC, SimonRit commented on include/rtkSARTConeBeamReconstructionFilter.hxx
> +    iterationReporter.CompletedStep();
The choice here is to report only iterations, not subsets. Should we consider reporting subsets as well?

2019-11-12 11:10 UTC, SimonRit commented on applications/rtkconjugategradient/rtkconjugategradient.ggo
> +option "output-every"   - "Output intermediate reconstruction after some iterations"                                  int    no
How come you have these options for rtkconjugategradient and not for rtksart? Maybe consider doing a section ggo ( similar to those in the applications directory).

2019-11-13 18:28 UTC, acoussat commented on wrapping/itkIterationReporter.wrap
> +itk_wrap_simple_class("itk::IterationReporter")
As far as I tested it, yes it is actually usable from Python. I have no idea if that line of code fits more into ITK's code than here though.

2019-11-13 18:33 UTC, acoussat commented on include/rtkSARTConeBeamReconstructionFilter.hxx
> +    iterationReporter.CompletedStep();
It would be nice, but I don't understand how that would work from the user's side to differentiate between `IterationEvent`s being emitted by the completion of an iteration or a subset. I guess one might create another event (`SubsetEvent`?). Do you have any other idea?

2019-11-13 18:35 UTC, acoussat commented on applications/rtkconjugategradient/rtkconjugategradient.ggo
> +option "output-every"   - "Output intermediate reconstruction after some iterations"                                  int    no
That was for testing purpose. Is such a behavior desired for every iterative filter?

2019-11-14 09:01 UTC, SimonRit commented on applications/rtkconjugategradient/rtkconjugategradient.ggo
> +option "output-every"   - "Output intermediate reconstruction after some iterations"                                  int    no
Yes but it should be off by default (which does not seem to be the case yet).

2019-11-14 09:02 UTC, SimonRit commented on include/rtkSARTConeBeamReconstructionFilter.hxx
> +    iterationReporter.CompletedStep();
You're right and I don't have a better idea... Let's leave it like this yet and implement a solution when someone needs it.

2019-11-14 09:04 UTC, SimonRit commented on wrapping/itkIterationReporter.wrap
> +itk_wrap_simple_class("itk::IterationReporter")
Yes, it fits better in ITK's code. Try submitting it and we'll see how they feel about it. See [CONTRIBUTING.md](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md).

2019-11-18 10:05 UTC, acoussat commented on wrapping/itkIterationReporter.wrap
> +itk_wrap_simple_class("itk::IterationReporter")
Done [here](https://github.com/InsightSoftwareConsortium/ITK/pull/1423), let's see what they think about it!

2019-12-09 10:49 UTC, SimonRit reviewed
Thanks. It seems to be close to a merge, right? If yes, I think you can prepare a one commit PR.

2019-12-09 10:49 UTC, SimonRit commented on applications/rtkadmmwavelets/rtkadmmwavelets.cxx
> +#include "rtkIterationCommands.h"
I would move all `#include "rtkIterationCommands.h"` to rtkMacro.h

2019-12-09 10:49 UTC, SimonRit commented on applications/rtkconjugategradient/rtkconjugategradient.cxx
> +  if(args_info.verbose_flag)
It seems that you haven't applied the new clang format... {} are now aligned with the if.

2019-12-09 10:49 UTC, SimonRit commented on applications/rtkconjugategradient/rtkconjugategradient.ggo
> +option "output-every"   - "Output intermediate reconstruction after some iterations"                                  int    no
Still not resolved, right?

2019-12-11 16:34 UTC, acoussat commented on applications/rtkconjugategradient/rtkconjugategradient.ggo
> +option "output-every"   - "Output intermediate reconstruction after some iterations"                                  int    no
Not yet, I should hopefully finish that before the end of the week! Sorry about the long time taken.

2019-12-11 16:36 UTC, acoussat commented on applications/rtkadmmwavelets/rtkadmmwavelets.cxx
> +#include "rtkIterationCommands.h"
Done in [commit b7710957e48a620f8c526a1445c82b46f3effd45](https://github.com/SimonRit/RTK/pull/266/commits/b7710957e48a620f8c526a1445c82b46f3effd45), thanks for the tip!

2019-12-16 12:15 UTC, acoussat commented on applications/rtkconjugategradient/rtkconjugategradient.ggo
> +option "output-every"   - "Output intermediate reconstruction after some iterations"                                  int    no
[Commit a8860d5c78fb7c6cdfecf8a5547c3e64d6943287](https://github.com/SimonRit/RTK/pull/266/commits/a8860d5c78fb7c6cdfecf8a5547c3e64d6943287) implements that in all iterative filters! (I admit I haven't thoroughly tested it on every filter.)

2019-12-16 12:16 UTC, acoussat commented on applications/rtkconjugategradient/rtkconjugategradient.cxx
> +  if(args_info.verbose_flag)
[Commit 0bc6b4d2c17a22be9f310dc81484cd075f26c504](https://github.com/SimonRit/RTK/pull/266/commits/0bc6b4d2c17a22be9f310dc81484cd075f26c504) should fix this.

2019-12-16 12:19 UTC, acoussat commented
I think everything should be alright now. Tell me if anything breaks or if the code feels weird!

2019-12-18 15:54 UTC, acoussat commented
Squashed all commits together. If this is fine with you, I guess this makes #150 obsolete and solves #114.
Next step would be to somehow document this feature and also add some tests.

2020-01-06 21:55 UTC, merged