ENH: Add rtkSimulatedGeometry python application
RTKConsortium/RTK pull request #328
Opened 2020-04-08 06:32 UTC by LucasGandel

2020-04-08 06:36 UTC, LucasGandel commented on applications/rtksimulatedgeometry/rtkSimulatedGeometry.py
> +  parser = argparse.ArgumentParser(description=
@SimonRit I chose to use argparse to avoid having to pip install external packages for argument parsing. I find it clear enough but let me know if you prefer another one (click?).

2020-04-08 06:37 UTC, LucasGandel commented on setup.py
> +        "lib/rtkSimulatedGeometry.py"
This makes scripts available in the path and allows users to call rtkSimulatedGeometry.py from anywhere just after pip installing rtk.

2020-04-08 06:39 UTC, LucasGandel commented on applications/rtksimulatedgeometry/CMakeLists.txt
> +  install(FILES rtkSimulatedGeometry.py
This installs the application script next to other wrapped files

2020-04-08 06:40 UTC, LucasGandel commented
@SimonRit This is how we can provide python applications to users. Let me know what you think.

2020-04-08 12:23 UTC, SimonRit requested changes
Unfortunately, I can't test the generated package because setup.py refers to ITK v5.1. Do you mind changing it to v5.1rc03 please? Thanks!

2020-04-08 12:23 UTC, SimonRit commented on applications/rtksimulatedgeometry/rtkSimulatedGeometry.py
> +  parser = argparse.ArgumentParser(description=
Ok sounds like a reasonable choice.

2020-04-08 12:23 UTC, SimonRit commented on applications/rtksimulatedgeometry/CMakeLists.txt
> +  install(FILES rtkSimulatedGeometry.py
In general, I still have the feeling that the cmake `install` commands in RTK are not right and should be replaced by, e.g., `itk_module_target_install`. But for this case I did not find a good macro in [ITKModuleMacros.cmake](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CMake/ITKModuleMacros.cmake).

2020-04-08 12:23 UTC, SimonRit commented on setup.py
> +        "lib/rtkSimulatedGeometry.py"
Great!

2020-04-08 12:23 UTC, SimonRit commented on applications/rtksimulatedgeometry/rtkSimulatedGeometry.py
> +#!/usr/bin/env python
Do you mind renaming it to rtksimulatedgeometry.py for consistency? Is `#!/usr/bin/env python` cross-platform?

2020-04-08 16:22 UTC, LucasGandel commented on applications/rtksimulatedgeometry/rtkSimulatedGeometry.py
> +#!/usr/bin/env python
Renaming is done. I tried it on windows and it works fine, might be just ignored

2020-04-08 16:24 UTC, LucasGandel commented on applications/rtksimulatedgeometry/CMakeLists.txt
> +  install(FILES rtkSimulatedGeometry.py
I understand, maybe such macro could help to improve RTK install process. But for this specific use case I think it is completely fine.

2020-04-09 15:28 UTC, SimonRit requested changes
Looks good and it seems to work although there are a bunch of warnings when loading the RTK package. These warnings are unrelated to the PR and I'll handle them, please don't do it, I'm in the middle of a large modification of the wrappings.

2020-04-09 15:28 UTC, SimonRit commented on applications/rtksimulatedgeometry/rtksimulatedgeometry.py
> +  parser.add_argument('output', metavar='output', help='Output file name')
Why are those not similar to the c++ application (--nproj and --output)?
My current feeling is that we should mirror the applications.

2020-04-09 15:28 UTC, SimonRit commented on applications/rtksimulatedgeometry/rtksimulatedgeometry.py
> +import argparse
If I anticipate the translation of all ggo files, how easy do you think it will be to have an "include" mechanism for ggo files such as [rtk3Doutputimage_section.ggo](https://github.com/SimonRit/RTK/blob/master/applications/rtk3Doutputimage_section.ggo)?

2020-04-09 16:42 UTC, LucasGandel commented on applications/rtksimulatedgeometry/rtksimulatedgeometry.py
> +import argparse
Very good question! I tried to find a mechanism to avoid duplicating the options but I could not find anything easy so far. The problem is to bring the included files in the package.
What I can think of is a mechanism similar to the one we have with CMake in C++, that would automatically parse and generate .py files to be included by the application script later to define the args object.
I can try to setup this and add it to this PR, unless you think of something else?

2020-04-09 16:46 UTC, LucasGandel commented on applications/rtksimulatedgeometry/rtksimulatedgeometry.py
> +  parser.add_argument('output', metavar='output', help='Output file name')
Agreed! But missing "--" indicates that it is a required argument for the script to run.
If those argument are not specified, the application prints the help section. It avoids having to check for the validity of those arguments in the code, but if you prefer to have only optional arguments I can change that.

2020-04-09 20:08 UTC, SimonRit commented on applications/rtksimulatedgeometry/rtksimulatedgeometry.py
> +import argparse
I guess the alternative is a small python module containing a function with the parser object as a parameter. Nothing urgent, we can leave it for later.

2020-04-09 20:11 UTC, SimonRit commented on applications/rtksimulatedgeometry/rtksimulatedgeometry.py
> +  parser.add_argument('output', metavar='output', help='Output file name')
As far as I understand, according to `rtksimulatedgeometry.py -h`, they become positional arguments:
```
positional arguments:
  n                     Number of projections
  output                Output file name
```
And indeed, `rtksimulatedgeometry.py -n 4 -o test.xml` gives `rtksimulatedgeometry.py: error: unrecognized arguments: -n -o`. So, I don't know how to use these positional arguments and yes, I prefer to pass them as optional arguments. Similarly, I would provide a default value for --rad_cyl and always pass the value. The result is the same, but it makes it clearer that no option is equivalent to rad_cyl=0.

2020-04-14 06:20 UTC, LucasGandel commented on applications/rtksimulatedgeometry/rtksimulatedgeometry.py
> +import argparse
I tried a few things as discussed on Friday, but could not find a clean solution so far.
I think we can leave it like this for now and improve it later depending on what is decided for C++ application (keep them or not).
Other changes about arguments have been addressed.

2020-04-14 20:11 UTC, SimonRit commented
Thanks again! To be continued...

2020-04-14 20:11 UTC, merged