Clang format linter
RTKConsortium/RTK pull request #330
Opened 2020-04-10 10:02 UTC by LucasGandel

@SimonRit This should run clang-format on PR and make the pipeline fail if the style is inconsistent. For branches pushed on the repo (not fork), style can automatically be fixed by adding the label action:ApplyClangFormat

2020-04-14 20:34 UTC, SimonRit requested changes
Ok thanks. Can you rebase your 3 commits on the updated #329? I have included the cmake/*cxx files, maybe you want to do the same. There is also one comment to address.
Locally, will this automatically apply the style as is done on a commit in the ITK repository?

2020-04-14 20:34 UTC, SimonRit commented on .gitattributes
> +examples/*.cxx                          our-c-style
Shouldn't this be `examples/**/*.cxx`?

2020-04-15 05:48 UTC, LucasGandel commented on .gitattributes
> +examples/*.cxx                          our-c-style
Nice catch! Thanks!

2020-04-15 05:54 UTC, LucasGandel commented
@SimonRit I made the changes you requested, thanks.
The linter will run automatically on each PR as soon as this is merged. 
For automatically fixing the style, you must add the "action:ApplyClangFormat" label to your PR. But this works only for branches pushed to your repository (not forks).
I am still working on the hooks to fix style locally but this is an additional check.

2020-04-15 19:14 UTC, merged