ENH: set division threshold for SART
RTKConsortium/RTK pull request #333
Opened 2020-04-14 09:18 UTC by acoussat

My attempt at fixing #151. From what I understood of the problem, this should suffice, but I might be missing something. I guess the modifications are automatically propagated to the Python wrappings.
One remark though: the current implementation allows setting a negative threshold. Is that a problem? [ITK seems to allow this behavior.](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Filtering/ImageIntensity/include/itkDivideOrZeroOutImageFilter.h#L74-L84)

2020-04-14 13:12 UTC, SimonRit requested changes
Well done, I had no idea it was that simple. Please address my comments and we're done.

2020-04-14 13:12 UTC, SimonRit commented on applications/rtksart/rtksart.cxx
> +    {
Check clang-format...

2020-04-14 13:12 UTC, SimonRit commented on include/rtkSARTConeBeamReconstructionFilter.h
> +  SetDivisionThreshold(ProjectionPixelType threshold);
Please use ITK macros `itkSetMacro itkGetMacro` for set and get (which is missing).

2020-04-14 13:12 UTC, SimonRit commented on include/rtkSARTConeBeamReconstructionFilter.hxx
> +  m_DivideProjectionFilter->SetThreshold(threshold);
I understand now why you haven't used ITK macros. I used to do similar things and RTK is full of such strategies. I now think it's not good because if you change the threshold value, the filter is not modified and the filter won't update if you call `Update()` again. My suggestion: create a `m_DivisionThreshold` filter parameter, Set Get it with the ITK macros and pass it to the filter in the `GenerateOutputInformation`. That's the most readable solution I believe.

2020-04-15 07:54 UTC, acoussat commented on applications/rtksart/rtksart.cxx
> +    {
Woops, I don't understand why `clang-format` didn't apply correctly on this file. Done!

2020-04-15 07:56 UTC, acoussat commented
Updated my commit. Hope everything is correct now!

2020-04-15 19:05 UTC, merged