Bug: Fix Zeng projectors
RTKConsortium/RTK pull request #347
Opened 2020-05-06 20:49 UTC by arobert01

2020-05-26 11:39 UTC, arobert01 commented
Ready to be merged

2020-05-27 09:21 UTC, SimonRit requested changes
Thanks! Two points to address before merge if you don't mind.

2020-05-27 09:21 UTC, SimonRit commented on include/rtkZengBackProjectionImageFilter.h
> +  static constexpr unsigned int InputSpaceDimension = TInputImage::ImageDimension;
Why not leave InputImageDimension? It is more common in ITK naming conventions.

2020-05-27 09:21 UTC, SimonRit commented on include/rtkZengBackProjectionImageFilter.hxx
>    // Find the center of the volume
Why does one need the center of the volume?

2020-07-02 13:26 UTC, SimonRit commented
What's the status of this PR @arobert01?

2020-07-02 15:03 UTC, arobert01 commented on include/rtkZengBackProjectionImageFilter.hxx
>    // Find the center of the volume
For now is needed because of the current implementation of the algorithm. There might be better way to do it without using the center of the volume. I can try to find another way if you prefer.

2020-07-02 15:06 UTC, arobert01 commented
For me it's ready to be merged. Do you want me to rebase my branch on master ?

2020-07-03 08:04 UTC, merged