ENH: Add convenience functions ReadGeometry and WriteGeometry
RTKConsortium/RTK pull request #475
Opened 2022-02-18 10:01 UTC by arobert01

These functions allow to simplify the C++ code for reading and writing a
geometry.

Inspired by the work done in ITK for reading
(https://github.com/InsightSoftwareConsortium/ITK/commit/aeea88b192) and
writing
(https://github.com/InsightSoftwareConsortium/ITK/commit/60b0984d4196841844424e33963e161f3f0c709d)
an image.

2022-02-21 16:10 UTC, SimonRit requested changes

2022-02-21 16:10 UTC, SimonRit commented on include/rtkThreeDCircularProjectionGeometryXMLFileReader.h
> +ReadGeometry(const std::string & filename);
The linking errors are probably caused by the absence of RTK_EXPORT for this function

2022-02-21 16:10 UTC, SimonRit commented on include/rtkThreeDCircularProjectionGeometryXMLFileWriter.h
> +                "WriteImage requires a raw pointer or SmartPointer.");
It doesn't hurt but I think it's not necessary (it won't compile anyway).

2022-02-21 16:10 UTC, SimonRit commented on include/rtkThreeDCircularProjectionGeometryXMLFileWriter.h
> +WriteGeometry(TGeometryPointer && geometry, const std::string & filename)
Why this double reference ``&&``?

2022-02-21 18:40 UTC, arobert01 commented on include/rtkThreeDCircularProjectionGeometryXMLFileWriter.h
> +WriteGeometry(TGeometryPointer && geometry, const std::string & filename)
This piece of code is a copy of what is done in the [WriteImage](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/IO/ImageBase/include/itkImageFileWriter.h#L245-L260) function in ITK. The `&&` allows to declare a [rvalue reference](https://www.artima.com/articles/a-brief-introduction-to-rvalue-references). In my understanding it allows to avoid the overload of the function for a parameter of type `const TGeometryPointer &` and one of type `TGeometryPointer &` ([perfect forwarding](https://docs.microsoft.com/en-us/cpp/cpp/rvalue-reference-declarator-amp-amp?view=msvc-170)).

2022-02-21 18:42 UTC, arobert01 commented on include/rtkThreeDCircularProjectionGeometryXMLFileWriter.h
> +                "WriteImage requires a raw pointer or SmartPointer.");
It is derived from [WriteImage](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/IO/ImageBase/include/itkImageFileWriter.h#L245-L260) function in ITK. Do you want me to remove it ?

2022-02-21 18:42 UTC, arobert01 commented on include/rtkThreeDCircularProjectionGeometryXMLFileReader.h
> +ReadGeometry(const std::string & filename);
Thanks I will add it.

2022-02-22 07:38 UTC, SimonRit approved these changes
Awesome!

2022-02-22 07:39 UTC, merged