ENH: Add superior and inferior clip images for Joseph-based forward projector
RTKConsortium/RTK pull request #543
Opened 2023-04-18 15:13 UTC by arobert01

The superior and inferior clip images define for each pixel of the projections the value of the superior and inferior clip of the ray emitted from that pixel. Each ray is clipped from
source+inferior_clip*(pixel-source) to
source+superior_clip*(pixel-source) with inferior_clip and superior_clip equal 0 and 1 by default.

2023-04-18 21:42 UTC, SimonRit requested changes

2023-04-18 21:42 UTC, SimonRit commented on include/rtkJosephForwardProjectionImageFilter.hxx
> +      double superiorClipImage = 1 - this->GetInferiorClipImage()->GetPixel(pixelIndex);
I would use an iterator on the InferiorClipImage instead to be more efficient

2023-04-18 21:42 UTC, SimonRit commented on include/rtkJosephForwardProjectionImageFilter.hxx
> +    if (isIntersectByRay && farDist > 0. && // check if detector after the source
Please split in two lines for clarity

2023-04-18 21:42 UTC, SimonRit commented on include/rtkJosephForwardProjectionImageFilter.hxx
> +    double superiorClip = 1. - m_InferiorClip;
Why has this been moved in the loop? It makes more sense to keep it out of the loop

2023-04-18 21:42 UTC, SimonRit commented on include/rtkJosephForwardProjectionImageFilter.hxx
> +      }
This is copied from ImageToImageFilter right? It's a pity there is not a way to avoid copy/pasting the code. Unless if you set the different inputs to 0 before calling the superclass method?

2023-04-18 21:42 UTC, SimonRit commented on applications/rtkforwardprojections/rtkforwardprojections.ggo
> +option "superiorclipimage" - "Value of the superior clip of the ray for each pixel of the projections (only with Joseph-based projector)" string no
Shouldn't this be in rtkprojectors_section.ggo?

2023-04-19 08:26 UTC, arobert01 commented on include/rtkJosephForwardProjectionImageFilter.hxx
> +    double superiorClip = 1. - m_InferiorClip;
Yes my bad, I moved it out of the loop

2023-04-19 08:46 UTC, arobert01 commented on applications/rtkforwardprojections/rtkforwardprojections.ggo
> +option "superiorclipimage" - "Value of the superior clip of the ray for each pixel of the projections (only with Joseph-based projector)" string no
Yes you are right, it should also be in rtkprojectors_section.ggo. In this case, we should also add the inferior and superior clip images in all the applications that could use the Joseph-based projectors  (rtkosem, rtksart, etc ...). Do you want me to do it ?

2023-04-19 08:47 UTC, arobert01 commented on applications/rtkforwardprojections/rtkforwardprojections.ggo
> +option "superiorclipimage" - "Value of the superior clip of the ray for each pixel of the projections (only with Joseph-based projector)" string no
Also should I add the superior and inferior clip images in the Joseph-based backprojectors ?

2023-04-19 08:48 UTC, SimonRit commented on applications/rtkforwardprojections/rtkforwardprojections.ggo
> +option "superiorclipimage" - "Value of the superior clip of the ray for each pixel of the projections (only with Joseph-based projector)" string no
Yes please if it's not too much work. I'm guessing it just have to be included in https://github.com/RTKConsortium/RTK/blob/master/include/rtkGgoFunctions.h?

2023-04-19 08:50 UTC, SimonRit commented on applications/rtkforwardprojections/rtkforwardprojections.ggo
> +option "superiorclipimage" - "Value of the superior clip of the ray for each pixel of the projections (only with Joseph-based projector)" string no
> Also should I add the superior and inferior clip images in the Joseph-based backprojectors ?

That's probably more work, let's not do it yet...

2023-04-19 09:00 UTC, arobert01 commented on include/rtkJosephForwardProjectionImageFilter.hxx
> +      }
In my understanding, in ImageToImageFilter the method verify that all the inputs are in the same physical space but in our case we just want to verify that, if given, the clip images are in the same physical space than the first input corresponding to the projections. I don't know if I can do this check by calling the superclass method.

2023-04-19 09:11 UTC, SimonRit commented on include/rtkJosephForwardProjectionImageFilter.hxx
> +      }
My idea is the following. You have three inputs, A B C. You want A and C to have the same information, not B. You can maybe do
```
tmpB = B
B = NULL
Superclass::VerifyInputinformation()
B = tmpB
```
?
A much more pleasant implementation would be to create a function in ImageBase, e.g., `HasSameInformation(Self *img2)` in which you would move most of the `ImageToImage::VerifyInputInformation` code to reuse it, e.g., here.

2023-04-19 09:43 UTC, arobert01 commented on applications/rtkforwardprojections/rtkforwardprojections.ggo
> +option "superiorclipimage" - "Value of the superior clip of the ray for each pixel of the projections (only with Joseph-based projector)" string no
> Yes please if it's not too much work. I'm guessing it just have to be included in https://github.com/RTKConsortium/RTK/blob/master/include/rtkGgoFunctions.h?

Actually, it's more work than I thought. For the reconstructions filters, like OSEM for example, the projectors are instantiate inside the method GenerateOutputInformation() of the filter : https://github.com/RTKConsortium/RTK/blob/abe956fbda210952ea3796d15e2077e6844fe1bd/include/rtkOSEMConeBeamReconstructionFilter.hxx#L82-L241 so to be able to give the clip images to the projector I think we also need to give them as input of the OSEM filter (or create setter and getter). Maybe I missing something simpler here ?

2023-04-19 09:59 UTC, arobert01 commented on include/rtkJosephForwardProjectionImageFilter.hxx
> +      }
Thanks for the ideas. I agree than the second solution is more elegant, I can do it and create a pull request on ITK side if you want.

2023-04-19 10:15 UTC, SimonRit commented on include/rtkJosephForwardProjectionImageFilter.hxx
> +      }
Of course I agree. Thanks!

2023-04-19 10:16 UTC, SimonRit commented on applications/rtkforwardprojections/rtkforwardprojections.ggo
> +option "superiorclipimage" - "Value of the superior clip of the ray for each pixel of the projections (only with Joseph-based projector)" string no
It would be exactly the same as what you've implemented for attenuation images. I don't remember how you did that and whether it would be a lot of work.

2023-04-27 14:56 UTC, arobert01 commented on include/rtkJosephForwardProjectionImageFilter.hxx
> +    double superiorClip = 1. - m_InferiorClip;
Actually it has to be in the loop since now the superior and inferior clip could be pixel dependent if clip image are given

2023-04-27 15:01 UTC, SimonRit commented on include/rtkJosephForwardProjectionImageFilter.hxx
> +    double superiorClip = 1. - m_InferiorClip;
Of course but you don't need to redo the calculation if there is no clip images... You can keep this out of the loop I believe.

2023-05-04 14:30 UTC, SimonRit requested changes
Thanks! Closely looking at this, I think that all iterative applications can set the attenuation, PSF and clip image parameters in existing methods SetForwardProjectionFromGgo and SetBackProjectionFromGgo. This would mean moving the projectors code in rtkosem to these functions. What do you think? Should we change this in this PR or do it in a subsequent PR?

2023-05-04 14:58 UTC, arobert01 commented
>

2023-05-05 07:49 UTC, SimonRit requested changes
Some minor suggestions to implement rapidly. Two things for the record:
- I think the code in `SetForwardProjectionFromGgo` can be moved to `CreateForwardProjectionFromGgo` to be used in `SetForwardProjectionFromGgo` and `rtkforwardprojections.cxx`
- Maybe --geometry should be moved in `rtkprojectors_section.ggo`.
But these points can be addressed in a follow-up PR.

2023-05-05 07:49 UTC, SimonRit commented on include/rtkJosephForwardProjectionImageFilter.h
> +   * than the first one. */
than -> as

2023-05-05 07:49 UTC, SimonRit commented on include/rtkJosephForwardAttenuatedProjectionImageFilter.hxx
> +    if (it.GetName() == "_1")
I'm not sure what happened here. `Primary` is no longer a valid name?

2023-05-05 07:49 UTC, SimonRit commented on include/rtkJosephForwardProjectionImageFilter.hxx
> +      }
As discussed, will be addressed separately.

2023-05-05 07:49 UTC, SimonRit commented on include/rtkJosephForwardProjectionImageFilter.hxx
> +    typename InputRegionIterator ::IndexType pixelIndex = itIn->GetIndex();
Is `pixelIndex` still used?

2023-05-15 07:57 UTC, arobert01 commented on include/rtkJosephForwardAttenuatedProjectionImageFilter.hxx
> +    if (it.GetName() == "_1")
Yes `Primary` is a valid name but it is not the same input as `_1`.  `Primary` corresponds to the input 0 (the projections stack) and `_1` to the input 1 (the volume). I changed it because before to check that the attenuation map and the volume had the same informations we were testing that all the inputs expect the projections were in the same physical space.  But this is no longer valid because, if given, the clip images should be in the same physical space than the projections. So in this piece of code I specifically test that the volume (`_1`) has the same information than the attenuation map (`_2`).

2023-06-16 07:42 UTC, merged