BUG: Fixes on Boellaard Scatter Filter
RTKConsortium/RTK pull request #547
Opened 2023-04-27 11:41 UTC by GabrieleBelotti

Changed the condition on AirThreshold value (less than AirThreshold now) and revisited the averaging of the "averageBehindPatient" value. Discussion on #454.

2023-04-27 13:53 UTC, SimonRit requested changes
I think the non negativity will be less often hit with the comment I made. As far as I can remember, the non negativity code is as you describe it and I don't have a better solution.

2023-04-27 13:53 UTC, SimonRit commented on include/rtkBoellaardScatterCorrectionImageFilter.hxx
> +      if (itInSlice.Get() <= m_AirThreshold)
Thanks, it's a good change!

2023-04-27 13:53 UTC, SimonRit commented on include/rtkBoellaardScatterCorrectionImageFilter.hxx
> +    if (npixelBehindPatient > 1)
I don't think this is correct. This new change means that if your patient is 1 pixel big or 1000000 pixels big in the projection domain, you have the same amount of scatter (considering that all pixels have the same attenuation). I need to take the time to derive the code from Boellaard's paper to make this clearer for you. More on this tonight or tomorrow...

2023-04-28 10:17 UTC, SimonRit commented
I think you can modify this PR with only the change on the threshold. The rest should stay I believe and it would be good to have a few documentation notes. If you'd like, I can prepare a new PR later on.

2023-04-28 11:46 UTC, GabrieleBelotti commented on include/rtkBoellaardScatterCorrectionImageFilter.hxx
> +    if (npixelBehindPatient > 1)
Will remove it!

2023-04-28 14:08 UTC, GabrieleBelotti commented
> I think you can modify this PR with only the change on the threshold. The rest should stay I believe and it would be good to have a few documentation notes. If you'd like, I can prepare a new PR later on.

Agreed on the documentation notes. I've made the proper corrections. Let me know if I should do anything else. I believe you should be able to squash commits when merging the pull request.

2025-04-25 13:52 UTC, merged

2025-04-25 13:54 UTC, SimonRit commented
Fixes #454.