Cuda array interface
RTKConsortium/RTK pull request #617
Opened 2024-09-06 12:24 UTC by LucasGandel

Implement changes required on the RTK side following the implementation of __cuda_array_interface__ in CudaCommon

Requires [ITKCudaCommon#42](https://github.com/RTKConsortium/ITKCudaCommon/pull/42)

2024-09-06 13:14 UTC, SimonRit reviewed
I would like to be able to compile both the CudaCommon latest release and master's head versions, following RTK's policy for ITK versions. In this case, it might be doable by testing whether `GetGPUBufferPointerPtr` is defined as is done in eb90fb42b9dca3fe8be373e2b7c9724e4c3b6156 for an ITK macro. Note the regular expression in the log. Do you want to give it a try or should I try to implement this?

2024-09-06 13:14 UTC, SimonRit commented on src/rtkCudaWarpForwardProjectionImageFilter.cxx
> +  float * pin = (float **)(this->GetInputProjectionStack()->GetCudaDataManager()->etGPUBufferPointer());
Typo here

2024-09-17 11:53 UTC, LucasGandel commented
> I would like to be able to compile both the CudaCommon latest release and master's head versions, following RTK's policy for ITK versions. In this case, it might be doable by testing whether `GetGPUBufferPointerPtr` is defined as is done in [eb90fb4](https://github.com/RTKConsortium/RTK/commit/eb90fb42b9dca3fe8be373e2b7c9724e4c3b6156) for an ITK macro. Note the regular expression in the log. Do you want to give it a try or should I try to implement this?

Should we add a target_compile_definition in ITKCudaCommon to peform such a check (e.g. "CudaDataManagerHasGetGPUBufferPointerPtr")? Or do you prefer to use the CudaCommon_VERSION as suggested in https://github.com/RTKConsortium/ITKCudaCommon/pull/42 ? Or something else ?

2024-09-17 11:55 UTC, LucasGandel commented on src/rtkCudaWarpForwardProjectionImageFilter.cxx
> +  float * pin = (float **)(this->GetInputProjectionStack()->GetCudaDataManager()->etGPUBufferPointer());
Nice catch thanks, it looks like my local build was outdated so I missed that somehow, and even more: it should be a cast to (float *) and not (float **)

2024-09-17 12:30 UTC, SimonRit commented
> Should we add a target_compile_definition in ITKCudaCommon to peform such a check (e.g. "CudaDataManagerHasGetGPUBufferPointerPtr")? Or do you prefer to use the CudaCommon_VERSION as suggested in [RTKConsortium/ITKCudaCommon#42](https://github.com/RTKConsortium/ITKCudaCommon/pull/42) ? Or something else ?

No preference, the second one sounds simpler to me.

2024-09-18 11:35 UTC, LucasGandel commented
@SimonRit To preserve backward compatibility with CudaCommon, it was also required to add checks in itkCudaImageRTK.wrap, as it uses CudaCommon_SOURCE_DIR which is undefined before CudaCommon 2.0.
CudaCommon_SOURCE_DIR is now also used to check if cudaCommonConfiguration.h exists, which will define CUDACOMMON_VERSION_MAJOR.

The linter is unhappy with the new #ifdef, let me know if you have any other feedback before I fix the style.Thanks

2024-12-05 14:25 UTC, SimonRit requested changes
This is ready to be merged IMO, thanks for this great work maintaining backward compatibility with the CudaCommon HEAD and the new PR. There are (weird) code style issues:
https://github.com/RTKConsortium/RTK/actions/runs/11798626855/job/32865225878#step:4:6
Can you fix them before I merge please?

2024-12-06 09:51 UTC, LucasGandel commented
> This is ready to be merged IMO, thanks for this great work maintaining backward compatibility with the CudaCommon HEAD and the new PR. There are (weird) code style issues: https://github.com/RTKConsortium/RTK/actions/runs/11798626855/job/32865225878#step:4:6 Can you fix them before I merge please?

Thanks! Style issues have been fixed (although they were definitely weird).

2024-12-06 10:32 UTC, SimonRit approved these changes
Thanks for addressing the style issue! BTW, ITK is working on an upgrade of clang, see e.g.
https://github.com/InsightSoftwareConsortium/ITK/pull/5012
https://github.com/InsightSoftwareConsortium/ITK/pull/5015
We should plan following this upgrade.

2024-12-06 10:33 UTC, merged